### ISSUE TITLE
Maintainer e-mail address bounces

### ISSUE THREAD

**Issue by zeileis** [djbetancourt-gh/funGp#25]
José @djbetancourt-gh I tried to contact you via e-mail regarding the publication of your `funGp` package in the Journal of Statistical Software (JSS). However, the e-mail bounced:

> The recipient's mailbox is full and can't accept messages now. Please try resending your message later, or contact the recipient directly.

Note that a valid maintainer address is vital for a package and such bouncing messages may lead to archival of the package on CRAN etc. Hence it would be great if you could fix the problems with your mailbox or switch to a different address. Please also get in touch with me through the JSS editorial system.

Thanks in advance!

**Comment by djbetancourt-gh** [comment]
Hi Achim @zeileis Thanks for your message, for your patience and diligence in searching ways to contact me and for the heads up about my @uninorte.edu.co email. I definitely don't take for granted that you would do any of that. It is an extraordinary gesture on your part.

I didn't reply right away because I wanted to be diligent too and let you know right away in my response that I had resolved the issue with my inbox. unfortunately, this is taking considerable time and now I think it might be better to contact you sooner and then continue working on that fix (Uninorte decided to suddenly reduce the storage capacity of graduates' accounts from 15GB to just 1GB...!! This happened just two weeks ago).

I just checked the JSS editorial system and replied to you there.

Thanks again for your big help!

**Comment by zeileis** [comment]
José, no worries, thanks for the follow-up. Resolving the problem on the end of the mailbox is certainly the best solution (if feasible). Good luck with tidying up your storage, fingers crossed that you will finish it soon! I'll also follow up in the JSS editorial system - but somewhat later today. Best wishes, Achim

**Comment by djbetancourt-gh** [comment]
Maintained address updated to the brand new fungp.rpack@gmail.com address.
